server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?useSSL=true
    username: root
    password: woaini1314
    druid:
          initial-size: 1
          min-idle: 1
          max-active: 10
          validation-query: SELECT 1
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: true
          max-open-prepared-statements: 20
          use-global-data-source-stat: true
  output:
    ansi:
      enabled: always

mybatis:
    type-aliases-package: 'xzp.xf.sql.vo'
    mapper-locations: classpath:xzp/xf/xml/*.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  config: classpath:Logback-spring.xml
  level:
    xzp.xf.sql.mapper: trace









